### ISSUE TITLE
Cannot get property 'empty' on null object

### ISSUE THREAD

**Issue by jorge-senger** [unbroken-dome/gradle-xjc-plugin#16]
I'm trying to configure multiple tasks but I got the following error:

Caused by: java.lang.NullPointerException: Cannot get property 'empty' on null object
at org.unbrokendome.gradle.plugins.xjc.XjcGenerate$_closure1.doCall(XjcGenerate.groovy:92)
at org.gradle.api.specs.internal.ClosureSpec.isSatisfiedBy(ClosureSpec.java:32)

This is my task:

task xjc_SPS(type: org.unbrokendome.gradle.plugins.xjc.XjcGenerate) {
source = fileTree('src/main/resources/xxx//') { include 'mySchema.xsd' }
outputDirectory = file('generated-sources/')
targetPackage = 'com.xxx'
}

**Comment by jorge-senger** [comment]
Strange that it only happens when I have multiple tasks for xjc. I followed the suggested approach on https://github.com/unbroken-dome/gradle-xjc-plugin/issues/5

**Comment by tkrullmann** [comment]
This should be fixed with 1.4.2, please try with the new version!
