### ISSUE TITLE
SourceSet specific episode configurations are not available for dependency declaration

### ISSUE THREAD

**Issue by gebhardt** [unbroken-dome/gradle-xjc-plugin#37]
I'm using Gradle 7.1 and added a custom SourceSet like this (the XSDs get unpacked from some dependencies in another task into the `$buildDir/xsds/custom` directory)

     sourceSets {
      custom {
          xjcSchema {
              srcDir("$buildDir/xsds/custom" )
              setIncludes(new HashSet(['path/to/my/schema.xsd', 'path/to/another/schema.xsd']))
          }
          xjcBinding {
              srcDir("$projectDir/src/main/bindings")
              setIncludes(new HashSet(['bindings_custom.xjb']))
          }
      }

If I use the `customXjcEpisodes` configuration in my dependencies like this

    dependencies {
       customXjcEpisodes 'my.group:my-artifact-with-an-episode-file:1.0'
    }

I get the following error

    A problem occurred evaluating project ':my-project'.
    > Could not find method v8XjcEpisodes() for arguments [my.group:my-artifact-with-an-episode-file:1.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

But if I add  'customXjcEpisodes'  to the configurations I'll receive this exception:

        Caused by: org.gradle.api.InvalidUserDataException: Cannot add a configuration with name 'customXjcEpisodes' as a configuration with that name already exists.
	        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.assertCanAdd(DefaultNamedDomainObjectCollection.java:213)
	        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:77)
	        at org.gradle.api.internal.AbstractValidatingNamedDomainObjectContainer.create(AbstractValidatingNamedDomainObjectContainer.java:47)
	        at org.unbrokendome.gradle.plugins.xjc.XjcPlugin.createInternalConfiguration(XjcPlugin.kt:160)
	        at org.unbrokendome.gradle.plugins.xjc.XjcPlugin.createInternalConfiguration$default(XjcPlugin.kt:158)
	        at org.unbrokendome.gradle.plugins.xjc.XjcPlugin$apply$3$1.execute(XjcPlugin.kt:102)
	        at org.unbrokendome.gradle.plugins.xjc.XjcPlugin$apply$3$1.execute(XjcPlugin.kt:15)
	        at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:112)
	        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction$1.run(DefaultCollectionCallbackActionDecorator.java:95)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	        at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
	        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:74)
	        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
	        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:74)
	        at org.gradle.api.internal.DefaultCollectionCallbackActionDecorator$BuildOperationEmittingAction.execute(DefaultCollectionCallbackActionDecorator.java:92)
	        at org.gradle.internal.ImmutableActionSet$SetWithFewActions.execute(ImmutableActionSet.java:285)
	        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:264)
	        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.doAdd(DefaultNamedDomainObjectCollection.java:113)
	        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:253)
	        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:79)
	        at org.gradle.api.internal.AbstractValidatingNamedDomainObjectContainer.create(AbstractValidatingNamedDomainObjectContainer.java:47)
	        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:71)
	        at org.gradle.api.internal.NamedDomainObjectContainerConfigureDelegate._configure(NamedDomainObjectContainerConfigureDelegate.java:39)
	        at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:65)
	        at build_96zah4zjotmure7ygo5d5ijo1$_run_closure4.doCall(D:\develop\git-repo\gda\gda\ablageadapter\build.gradle:101)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	        at org.gradle.util.internal.ClosureBackedAction.execute(ClosureBackedAction.java:72)
	        at org.gradle.util.internal.ConfigureUtil.configureTarget(ConfigureUtil.java:155)
	        at org.gradle.util.internal.ConfigureUtil.configureSelf(ConfigureUtil.java:143)
	        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:91)
	        at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:38)
	        at org.gradle.util.internal.ConfigureUtil.configure(ConfigureUtil.java:104)
	        at org.gradle.util.internal.ConfigureUtil$WrappedConfigureAction.execute(ConfigureUtil.java:167)
	        at org.gradle.internal.extensibility.ExtensionsStorage$ExtensionHolder.configure(ExtensionsStorage.java:173)
	        at org.gradle.internal.extensibility.ExtensionsStorage.configureExtension(ExtensionsStorage.java:64)
	        at org.gradle.internal.extensibility.DefaultConvention.configureExtension(DefaultConvention.java:364)
	        at org.gradle.internal.extensibility.DefaultConvention.access$500(DefaultConvention.java:45)
	        at org.gradle.internal.extensibility.DefaultConvention$ExtensionsDynamicObject.tryInvokeMethod(DefaultConvention.java:301)
	        at org.gradle.internal.metaobject.CompositeDynamicObject.tryInvokeMethod(CompositeDynamicObject.java:98)
	        at org.gradle.internal.extensibility.MixInClosurePropertiesAsMethodsDynamicObject.tryInvokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:34)
	        at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.tryInvokeMethod(BasicScript.java:135)
	        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
	        at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:84)
	        at build_96zah4zjotmure7ygo5d5ijo1.run(D:\develop\git-repo\gda\gda\ablageadapter\build.gradle:100)
	        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	        ... 141 more

Is it possible the the configuration is added to late for being used in the `dependency` section?

**Comment by gebhardt** [comment]
I found the solution:

You have to define the `sourceSets` section *before* the `dependencies` section.
