### ISSUE TITLE
Plugin fails with Java 10

### ISSUE THREAD

**Issue by wadoon** [unbroken-dome/gradle-xjc-plugin#6]
Applying the plugin causes a `NoClassDefFoundError` under Java 10. 
It is working with Java 8.

```
[...]
Caused by: java.lang.NoClassDefFoundError: com/sun/org/apache/xml/internal/resolver/tools/CatalogResolver
        at org.gradle.internal.reflect.ClassInspector.inspectClass(ClassInspector.java:72)
        at org.gradle.internal.reflect.ClassInspector.visitGraph(ClassInspector.java:56)
        at org.gradle.internal.reflect.ClassInspector.inspect(ClassInspector.java:36)
        at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:288)
        at org.gradle.api.internal.AbstractClassGenerator.inspectType(AbstractClassGenerator.java:243)
        at org.gradle.api.internal.AbstractClassGenerator.generateUnderLock(AbstractClassGenerator.java:115)
```

Gradle: 4.7, java version "10" 2018-03-20, Plugin: 1.1.3

**Comment by tkrullmann** [comment]
Hi! Thanks for the heads-up.
This is because the catalog resolution has been moved to the "public" `javax.xml` package starting with JDK 9.
I'd rather not break compatibility with Java 8 (which is still the LTS release), so I'll have to add the `xml-resolver` library as a proper dependency.
